### ISSUE TITLE
Not able to detect object when object is placed near the end of desk

### ISSUE THREAD

**Issue by rajnishtripathi10121995** [mikeferguson/simple_grasping#8]
I'm testing object pickup with kinova arm, object pick and place is successful when object is placed at the centre of desk but object is not detected when it  is placed near the end of desk.
Object is not detecting and I'm getting following logs: 
![image](https://user-images.githubusercontent.com/105341076/172209858-e2e7488e-9061-46c0-8a91-86780344ebf2.png)

**Comment by mikeferguson** [comment]
If you set the "~use_debug" parameter to true, you'll get two new debugging topics - one for the surface and one for the objects. That might help determine what is going on (for instance, do we just not see the surface - from your image it looks like maybe that object location would segment the support surface in two, since you won't see the support surface behind the object)

**Comment by rajnishtripathi10121995** [comment]
After changing the pose of arm from top view, now it is able to detect object. Surface behind object is not visible that's why it is not able to detect it. Thanks
